### PR TITLE
BUG: labels did not load on windows machine, adapt to modified HelperBox class

### PR DESCRIPTION
**Pull request by che85**
- fixed path for segmentations by only using the filename itselfs and extracting structure and timestamp of this

### CODE REVIEW

**Comment by fedorov** [comment]
Christian, this is not a valid pull request. Do you understand why?

**Comment by che85** [comment]
Oh yes I see. It makes the reverts the changes of another pull request that your already merged.

**Comment by fedorov** [comment]
It shows me as the commit author. I am not sure how this happened!

**Comment by che85** [comment]
Oh that's tricky.

**Comment by che85** [comment]
Ok, to make this clean, I will create another branch and a new pull request. Or what do you think?
Maybe one for the failing label load and one for the changes of HelperBox

**Comment by fedorov** [comment]
yes, this is a good idea. I don't understand what happened in this branch.

make sure you update master, since I merged
https://github.com/fedorov/PCampReview/pull/57

I think if you follow the workflow, it should be fine:

1) update master
2) create new branch
3) commit
4) push branch to github

**Pull request closed without merging**
