### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by che85**

### CODE REVIEW

**Comment by che85** [comment]
I am not sure, why the old commits also occur although I made a rebase

**Comment by rweiss42** [comment]
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by rweiss42** [comment]
I'm not sure the commits actually occurred, I think it just concatenated all of your commit messages. I think you can avoid this by "rewording" your commit message when you do the rebase, but ultimately, I think it's ok to see all of the steps you went through

**Comment by fedorov** [comment]
So we looked into this with Christian together. He is using Tortoise (a Windows GUI thingy) to do this, and apparently he needs to do a commit after resolving conflicts for each of the original commits.

When I do rebase from command line, I can do "git add" after resolving each of the commits, and then I have a clean history where each of the original commits has a single one in the rebased branch history.

Christian is going to look into using SourceTree as an alternative to Tortoise, and we'll see if this resolves the problem.

**Comment by rweiss42** [comment]
For the record, I've always done git rebase on the command line following the instructions in the link above and yes, also use git add + git rebase --continue to resolve conflicts when rebasing.  Not sure how gracefully SourceTree does rebases as I have not tried it.

**Comment by fedorov** [comment]
Thanks Robin - this is good to know! I suggested Christian to use SourceTree because I thought that's what he used, and you had good experience with it.

I always use command line, but Christian is used to GUI tools, which I understand. Let's see what he finds out about SourceTree. We agreed it will be nice to figure this issue out to avoid duplicate commits in the history.

**Comment by rweiss42** [comment]
For me: SourceTree = clone, fetch, push, pull, commit, branch, stash. CLI = rebase.

**Comment by che85** [comment]
SourceTree is great but for rebasing it also produces for every single merged commit a new commit instead of just adding one commit for ALL merged commits.

**Comment by rweiss42** [comment]
When you did the rebase did you squash your commits?  See https://answers.atlassian.com/questions/213902/in-sourcetree-how-do-i-squash-commits and https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request (the section on squashing changes)

**Comment by che85** [comment]
Maybe I should try that. Just to figure out the best practice.

**Comment by fedorov** [comment]
I prefer not to squash. The command line workflow allows that.

---

**Comment by che85** [comment]
That's really hard to merge everything after changing so many lines of code. Especially when using only an editor....

**Comment by fedorov** [comment]
@rweiss42 I met with Christian today, and we decided to start from fresh instead of resolving conflicts, as the latter turned out quite challenging - too many of them. Please hold off any major PRs if you have any in mind, and let's have Christian finish his refactoring without any major conflicts.

@che85 If you like, feel free to have multiple pull requests if you want us to test things in smaller chunks, instead of preparing one big PR.

**Comment by rweiss42** [comment]
Sounds good

**Pull request closed without merging**
