### PR TITLE
ENH: check for preprocessed directory and provide preprocessing from mpReview

### LINKED ISSUE #88: Using mpReview without explicitly using mpPreprocessor first
It would be great if mpReview could offer functionality for minimizing the need of user input. 

Proposal: If directory with none mpReview compatible directory structure is found which is eligible for mpReviewPreprocesser, a prompt could be opened which shows:
- Output directory where to store the mpReview-"project"(DICOM files would automatically organized).
  mpReviewPreprocesser would be executed and input path is after execution set to the output directory of mpReviewPreprocesser

@rweiss42 @fedorov What do you think about that?

### LINKED ISSUE #99: No check done for ensuring that current input directory is mpReview preprocessed directory
Following scenario:
1. User selects a input directory which has sub folders
2. mpReview interprets those directories as studies (where actually should already been done some check with feedback if it fails)
3. going to tab 2 (series selection) throws exception caused by missing RESOURCES subdirectory....

### LINKED ISSUE #105: DilateEffect needs to be available
In order to be able to skip every second slice while for instance segmenting the whole gland, we need to add back again the DilateEffect

### PR DESCRIPTION
**Pull request by che85**
fixes #88, fixes #99, fixes #105

### CODE REVIEW

**Comment by che85** [comment]
can be merged...

**Comment by fedorov** [comment]
I wanted to review and test this one, thanks for the reminder!

---

**Comment by fedorov** [comment]
Sorry for the long delay.

I think it would be better if instead of creating the output directory as done right now, user is given an option to change that output location, or leave it as is. Directory with the source data may simply not be writeable.

**Comment by che85** [comment]
Now the user has the chance to browse for an output directory. When the user chose the input directory, he/she is again prompted

**Comment by fedorov** [comment]
Looks like dilate effect commit got into here by accident, or was it intended?

**Comment by che85** [comment]
Actually it was on purpose. I also changed the initial text of that pull request. Maybe I should update the title as well

**Comment by fedorov** [comment]
ah, ok - no problem

**Pull request merged**
