### PR TITLE
STYLE: Refactor showExitStep4Warning()'s confirm dialog into a re-usa…

### PR DESCRIPTION
**Pull request by rweiss42**
…ble method.

### CODE REVIEW

**Comment by mehrtash** [comment]
:+1:

**Comment by rweiss42** [comment]
Just out of curiosity, who decided to have showExitStep4Warning() return True on No and False on Yes?  Definitely took me a second to sort that one out... ;)

**Comment by fedorov** [comment]
@rweiss42: the answer to your question is the github "Blame" button ;)

image

**Comment by fedorov** [comment]
Also, what Blame doesn't say is that it's @fedorov who was supposed to review this code before it was merged, so he is actually the one to at least share the blame! ;)

**Comment by fedorov** [comment]
@rweiss42 I am sure this is unrelated to your commit, but while testing I again came across the issue with the LUT popup we thought we resolved ... :(

image

**Pull request merged**
