### PR TITLE
BUG: Need to check for -label_# when doing propagate to make sure we …

### PR DESCRIPTION
**Pull request by rweiss42**
…don't propagate on top of an existing structure

### CODE REVIEW

**Comment by fedorov** [comment]
What would be the scenario where we might have label_# ? I thought (hoped!) this should not happen. No issue with the PR, just wanted to understand the background for this.

**Comment by rweiss42** [comment]
That's an extremely good question actually.  Trying to track that down now.  My mission for this morning is to try to break PCamp before I show it to Aytek again tomorrow.  I'm trying to figure out exactly what the steps were that led me to this situation since I was very quickly clicking around trying to make sure things wouldn't break and I noticed that I was starting to get label_# volumes.

**Comment by fedorov** [comment]
Hmmm... yes, definitely it would be much better to track down why that was happening. It may be an indication of a bigger issue somewhere.

**Comment by rweiss42** [comment]
So the issue is with CreateAndAddLabelVolume not respecting the name parameter.  Doing an explicit SetName on the new label volume when doing a propagate should fix this.

**Comment by fedorov** [comment]
Ok! Can you confirm the scene does not have the node with the requested name at the time CreateAndAddLabelVolume is called?

**Comment by rweiss42** [comment]
Yes, that was the hope with this line: https://github.com/fedorov/PCampReview/pull/70/files#diff-75cba40d066c6ffacf55f971f0cf2b37R1613

**Comment by rweiss42** [comment]
If there is a node that matches the name of the node we're about to create (or there's one that somehow was created with _#) then don't proceed with propagate.

**Comment by rweiss42** [comment]
now that I look at it, that's a really obfuscated line of code...

**Comment by fedorov** [comment]
No, sorry ... what I meant to say, when you actually test and call
CreateAndAddLabelVolume
and it does not respect the name parameter - can you confirm there's no
node with the same name in the scene at that time? If the answer is no,
then I am not sure why CreateAndAddLabelVolume would not respect the
parameter...

**Comment by rweiss42** [comment]
Confirmed.  You can re-produce this easily:

volumesLogic = slicer.modules.volumes.logic()
labelNode = volumesLogic.CreateAndAddLabelVolume(slicer.mrmlScene, slicer.util.getNode('MRHead'), 'foo')
slicer.mrmlScene.RemoveNode(labelNode)
labelNode = volumesLogic.CreateAndAddLabelVolume(slicer.mrmlScene, slicer.util.getNode('MRHead'), 'foo')

**Comment by rweiss42** [comment]
as you create and remove nodes, you end up with foo_# which keeps increasing

**Comment by fedorov** [comment]
Thanks! I do feel better now ;)

**Pull request merged**
