### PR TITLE
ENH: Add ability to delete structures

### PR DESCRIPTION
**Pull request by rweiss42**

### CODE REVIEW

**Comment by mehrtash** [comment]
I think it would be useful to have this functionality in editor too. So probably it would be better to add it in editor instead of PCampReview.

**Comment by fedorov** [comment]
Good point! @rweiss42 would you like to handle it this way if ok with @pieper?

**Comment by rweiss42** [comment]
Interesting idea.  I agree that it is probably most natural for this functionality to live within editor.  There is already a Delete Structures button in the editor but this blows away all structures not just selected.  I'd be happy to talk with @pieper regarding this.

**Comment by pieper** [comment]
Sounds like a great idea - there is already a concept of the currently
selected structure so we could add a way to delete it.  One option would be
to introduce a context menu to the structure list.  Then we could also
include an option to increase the merge priority of the structure.

**Comment by rweiss42** [comment]
When we delete a structure from the editor's table via context menu (or button or whatever) we also need to have our code do some cleanup (delete some files from disk and also kill the corresponding model nodes).  Possible n00b question: How would we want to architect this functionality to make it possible for our code to detect the delete structure event?  My idea would be to connect the delete event from Editor to a method in our code so that in addition to Editor doing its delete method, we also kick off ours. This is possible/kosher, yeah?

**Comment by pieper** [comment]
I'd like to see the feature have a clean implementation in the editor, but
then how it gets used in PCamp is not clear to me.  It's been quite a while
since I looked, but I think deleting a single structure in the editor will
be pretty simple, basically just deleting the volume node and maybe doing
some additional cleanup.

**Comment by rweiss42** [comment]
As far as I can tell, all that you would need to do is grab the name of the label map associated with the selected structure by grabbing the text of column 3 and removing that node from the scene.  Is there anything else that would need to get cleaned up?

The question I was asking was more of a pcampreview related issue.  We have other things that need to get cleaned up on deletion of a structure and I was just trying to think ahead.  I think i've answered my own question however so no worries.

**Comment by pieper** [comment]
Sounds good to me.

**Comment by rweiss42** [comment]
Any chance someone can point me to an example for how to set up a context menu?  That is, if we are committed to doing it like this...  Otherwise I can shove this logic into a button.

As I mentioned, we need to do some additional cleanup when a specific structure is deleted.  Will it be possible to connect() an additional method to a context menu item from inside our code?

**Comment by pieper** [comment]
The extension wizard has some nice usage of Qt from python and has context
menu [1] example.  If I were starting from scratch I'd want to do some of
the widget customizations using a similar approach (I hadn't known it was
possible to inherit python classes from qt classes at the time the editor
was written).

[1]
https://github.com/Slicer/Slicer/blob/121d28f3d03c418e13826a83df1ea1ffc586f0b7/Modules/Scripted/ExtensionWizard/ExtensionWizardLib/EditableTreeWidget.py

**Comment by rweiss42** [comment]
Well I took a look at the EditableTreeWidget yesterday but hit some issues with trying to make it work in Editor.  Not sure what the problem was, but after taking a closer look at it I'm also not sure I understand enough about qt slots to determine whether or not we'd be able to hang additional methods off of the context menu delete action as we'll need to do.

In any event, I'm reasonably confident something could be put together that makes use of context menus but I'm not sure I have enough idle cycles right now to spend time on this.  I'd be happy to propose a PR for adding a button to Editor that deletes the currently selected structure.  We could also put this on the back burner for now and just stick with having the delete structure button implemented in our PCampReview code instead of Editor (and one day when Editor has a delete structure function modify accordingly). What do you think @pieper @mehrtash ?

**Comment by fedorov** [comment]
+1 for delete button vs no no delete function in editor

**Comment by pieper** [comment]
Yes, a delete function is a good solution.  Ideally it would be disabled
when there is no structure selected, but that's not really essential.

**Comment by rweiss42** [comment]
Sounds good to me.  Two small questions:

1) I'll plan to add an additional button to the allButtonsFrame next to the existing delete button.  Will this be too crowded?
2) We already have an object named DeleteStructureButton. Are we happy calling the new one DeleteSelectedStructureButton?

**Comment by pieper** [comment]
I suspect both will fit.  Maybe name one Delete All and the other Delete
Selected.  Or you could get (just a bit) fancier and listen for selection
signals from the list and update the text and behavior of a single button
accordingly.

**Comment by mehrtash** [comment]
How about one Delete button? 
It would be disabled when there is no structure selected. Adding select all/none check boxes for selecting all of the structures to delete.

**Comment by rweiss42** [comment]
The only think I was concerned about is fiddling with the existing DeleteStructures button in case someone else's code is expecting it to have a particular behavior/name/configuration.

**Comment by pieper** [comment]
I don't think that anyone is too dependent on the current DeleteStructures
button.  Can't stand in the way of progress.

**Comment by rweiss42** [comment]
cool beans.  so long as I have your blessing i'll see what I can whip up.  stay tuned.

**Comment by fedorov** [comment]
Robin, has this been harmonized with the latest changes to Slicer delete structure functionality? Please let me know if this is ready for testing.

**Comment by rweiss42** [comment]
Yes?  The code itself should be fine and i've tested against the updated editor code but I think I may have done some silly gitting and branched when I should have merged or vice versa... (there is code for the confirm dialog in here which was merged in a different PR for example).  Want to give it a test and see how it goes?

**Comment by rweiss42** [comment]
I have a version of the same stuff in a 'clean' branch if you want me to PR from that one instead.

**Comment by fedorov** [comment]
I ran into a compile error in Slicer while updating my build to test this commit: https://github.com/Slicer/Slicer/commit/7b816afddda7a180f1f2dcae7357ed8264c2ae82#commitcomment-11142607

Waiting for @jcfr to respond.

**Comment by fedorov** [comment]
Robin, looking at the commit history and details - can you make a new PR? I don't know why merge is possible, but it does not look right or clean to me.

**Comment by fedorov** [comment]
resolved in #39

**Pull request closed without merging**
