### PR TITLE
Segmentation files viewable by other users

### LINKED ISSUE #151: Support multiuser segmentation
From discussions with @DoraSzasz, they were having problems when several users work on the same series because one user cannot see the segmentation of another. 

There are several ways for supporting that:
- display all segmentations available (regardless of the creator)
- display only all most recent segmentations (if several segmentations of the same object have been found)
- users might want to override a segmentation of another user which should a) give a warning and b) log this somehow and keep the old label in place and save the new one

@fedorov Any thoughts on this?

### PR DESCRIPTION
**Pull request by DoraSzasz**
Loading the segmentation files even if they were created by a different
user.

fixes #151

### CODE REVIEW

**Comment by che85** [comment]
LGTM

**Comment by fedorov** [comment]
I am not sure it is that simple. In some situations I think it might make more important that the user can modify only those segmentations created by that user. Some ideas:

 - add view or read-only mode where any segmentation could be seen (should be clear who did what segmentation?
 - add a drop-down list of all users who contributed segmentations for the given series to support viewing?
 - when user edits a segmentation, make sure that it is saved under that user name, even if it was started from an existing segmentation done by someone else

ideas?

**Comment by DoraSzasz** [comment]
Yes, indeed, the solution can be improved. This solution we used at
UChicago because I know for sure that just one user is doing the
segmentation. The others are just viewing it.  For the moment, anyone can
see the other segmentation files. If the segmentation file is modified and
saved, there will be 2 versions of the segmentation.

I think the view-only mode is very useful. I can do this for the moment.
And then manage saving the modified segmentation. Andrey is right, we have
to save, for a structure,  only the segmentation modified by the last user.

**Comment by fedorov** [comment]
Superseded by #167

**Pull request closed without merging**
