### PR TITLE
Refactoring code

### LINKED ISSUE #54: Refactor the code
Simplify/clean up the code without changing any of the functionality.

### PR DESCRIPTION
**Pull request by che85**
fixes #54

### CODE REVIEW

**Comment by che85** [comment]
I am not sure, why I am only shown by C. H as the author of these commits.

**Comment by fedorov** [comment]
To answer your question - you need to set up your name, see instructions https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup (command line, I hope this can also be done from GUI)

Note that your commit has conflicts - your branch was just 2 commits behind. Can you fix?

**Comment by fedorov** [comment]
@rweiss42 let's review this before moving on with other issues, to avoid merge conflicts?

**Comment by rweiss42** [comment]
Yeah, sounds good.  I'm adding issues just to keep track of them.  Is this PR ready to be reviewed?

**Comment by fedorov** [comment]
yes, it should be ready, Christian is telling me. I need to work on something else first today, but will work on reviewing it this week.

**Comment by che85** [comment]
It's not yet finished, but I don't want to commit too much, so I will wait for the results before I want to continue with that.

**Comment by fedorov** [comment]
yes, that is fine. I meant to say that the commits that are already there should be working and can be reviewed independently of the whole issue not being completed.

**Comment by rweiss42** [comment]
Looks good to me.

Extremely minor comment/question: Would renaming getAllWidgets() to getAllSliceWidgets() make sense?  Are there other types of "widgets"?

**Comment by che85** [comment]
I think getAllSliceWidgets() fits better ...

**Comment by rweiss42** [comment]
Do we have a time frame on getting this wrapped up?

**Comment by fedorov** [comment]
My fault - I somehow am not getting notifications when Christian commits changes, so I didn't realize it was done yesterday.

**Pull request merged**
