### PR TITLE
MultiVolumeExplorer integration, fiducials from labelmaps and GUI adaptions

### LINKED ISSUE #80: MultiVolumeExplorer integration (partly - not all features are needed) for setting fiducials
What you think about my current implementation?

I added an new workflow step and icon.

screenshot 2015-08-06 11 40 16

TODO: 
- implementation of fiducials setting
- discarding fiducials when discarding changes

### PR DESCRIPTION
**Pull request by che85**
fixes #80

### CODE REVIEW

**Comment by fedorov** [comment]
@che85 thanks! Can you make a pull request for MultiVolumeExplorer with your changes as well?

@rweiss42 we worked on these changes to support our interventional workflow, they are all here to support one "feature" in a way. Sorry it is all lumped under one PR, but Christian nicely separated the features into individual commits.

**Comment by fedorov** [comment]
I have this runtime error when I try:

```
Switch to module:  "PCampReview"
qSlicerMultiVolumeExplorerSimplifiedModuleWidget:init() called
Traceback (most recent call last):
  File "/Users/fedorov/github/PCampReview/PCampReview.py", line 270, in setup
    self.multiVolumeExplorer.setup()
  File "/Users/fedorov/local/builds/Slicer4-Debug/Slicer-build/lib/Slicer-4.4/qt-loadable-modules/Python/qSlicerMultiVolumeExplorerModuleWidget.py", line 31, in setup
    self.setupInputFrame()
  File "/Users/fedorov/github/PCampReview/PCampReview.py", line 2165, in setupInputFrame
    self._bgMultiVolumeSelectorLabel.hide()
AttributeError: PCampReviewMultiVolumeExplorer instance has no attribute '_bgMultiVolumeSelectorLabel'
```

**Comment by che85** [comment]
I had some uncommitted changes. Should work now.

**Comment by fedorov** [comment]
If the user has a setting where input data directory is non-empty, the studies list should be populated automatically. As it is now, the list is empty until I re-select the input directory. Also, there should be label above the list of studies: "Studies found:" for example.

**Comment by fedorov** [comment]
Are all the changes committed now? 

I have this on going to step 2:

```
Traceback (most recent call last):
  File "/Users/fedorov/github/PCampReview/PCampReview.py", line 270, in setup
    self.multiVolumeExplorer.setup()
  File "/Users/fedorov/local/builds/Slicer4-Debug/Slicer-build/lib/Slicer-4.4/qt-loadable-modules/Python/qSlicerMultiVolumeExplorerModuleWidget.py", line 33, in setup
    self.setupAdditionalFrames()
  File "/Users/fedorov/github/PCampReview/PCampReview.py", line 2181, in setupAdditionalFrames
    self.layout.addWidget(self.popupChartButton, 3, 0, 1, 3)
ValueError: Called addWidget(QWidget w) with wrong number of arguments: (QPushButton (QPushButton at: 0x7f8568f34c20), 3, 0, 1, 3)
Traceback (most recent call last):
  File "/Users/fedorov/github/PCampReview/PCampReview.py", line 199, in onTabWidgetClicked
    self.onStep2Selected()
  File "/Users/fedorov/github/PCampReview/PCampReview.py", line 1071, in onStep2Selected
    self.editorWidget.helper.masterSelector.blockSignals(True)
AttributeError: PCampReviewWidget instance has no attribute 'editorWidget'
```

**Comment by che85** [comment]
yes, but please also update the PCampReview

**Comment by che85** [comment]
In my case the studies table is automatically filled with available studies...

**Comment by fedorov** [comment]
You are right, I was one commit off. And yes, now the studies table is populated automatically. Thanks!

**Comment by fedorov** [comment]
This looks good, and works as expected. Thanks a lot!

@rweiss42 we reshuffled the translate label and view orientation to Advanced settings - are these common operations for your users? Do you have a concern about this change? The UI is not perfect, we can definitely improve... Please let us know if you have any other concerns.

**Comment by che85** [comment]
@fedorov What about the playback, when a series is selected which is no multivolume? The layers are therefore also no multi volumes --> no other frames available. What to do with the slider then? Hide it? and only display it, when a series with a multi volume is selected?

**Comment by fedorov** [comment]
yes, it makes sense to hide the multivolume explorer frame completely when there is no multivolume series selected

**Comment by che85** [comment]
I think that's it

**Comment by fedorov** [comment]
@rweiss42 can you let us know when you will have a chance to take a look?

Please let me know if you would prefer to have a call to discuss this.

**Comment by rweiss42** [comment]
thanks for reminding me, this got buried in my inbox.  I just downloaded the branch and i get

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/robinweiss/Downloads/PCampReview-integrateMultiVolumeExplorer/PCampReview.py", line 12, in <module>
    from qSlicerMultiVolumeExplorerModuleWidget import qSlicerMultiVolumeExplorerSimplifiedModuleWidget, MultiVolumeExplorerLogic
ImportError: cannot import name qSlicerMultiVolumeExplorerSimplifiedModuleWidget

Does this depend on a new version of the MultivolumeExplorer that i need to get elsewhere as well?

**Comment by fedorov** [comment]
Yes, this does depend on the updated MultivolumeExplorer, which has already been integrated into Slicer. So if you update and rebuild Slicer, or use today's nightly (assuming it exists and works!), it should be fine.

**Comment by rweiss42** [comment]
MultiVolumeExplorer stuff aside (still needs to be resolved), I had an issue with WindowLevelEffects.  I didn't have the WindowLevelEffect module added and so https://github.com/fedorov/PCampReview/pull/83/files#diff-75cba40d066c6ffacf55f971f0cf2b37R317 got confused.  Do we want to make WindowLevelEffect a strict dependency of PCampReview?

**Comment by fedorov** [comment]
Indeed, I can reproduce the problem with MVE. Somehow Christian missed your emails. Yes, we should make WindowLevelEffect a strict dependency.

**Comment by fedorov** [comment]
@rweiss42 we identified the problem and the fix should be easy. Really sorry I missed this in my testing. I guess I did the test before the final commit in the branch was made, that PR was a moving target ... Hopefully Christian will have a fix before leaving, otherwise I will look into it.

**Comment by che85** [comment]
Ok it should be fixed now. Sorry for that

**Comment by fedorov** [comment]
Robin, you will need to use the current master of MVE

**Comment by fedorov** [comment]
Robin, any updates?

**Comment by rweiss42** [comment]
Hey!  Sorry, it's been pretty crazy around here...

Everything seems to work with the latest slicer nightly now.  I like these additions.  The patient ID and data directory above the segmentation tools is nice.  Bringing in MVE for real (instead of my hack/reproduction) looks really good.  I like the charting as well.  From what I can tell from testing, nothing has been broken.

As you note, our on-going shuffling around of UI elements appears to be continuing.  I think for now this is fine however.  Merge away!

**Comment by rweiss42** [comment]
The color node issue pops up in this branch but it should be resolved when merging into the current master, right?

**Comment by fedorov** [comment]
Which color node issue? The one you fixed here: https://github.com/fedorov/PCampReview/pull/84 ?

**Comment by rweiss42** [comment]
indeed.

**Comment by rweiss42** [comment]
yeah, everything should be good to go.

**Comment by fedorov** [comment]
yes, right - that one is already in. Ok, I will merge then. Definitely UI can and should be improved. We should maybe plan a brainstorm hangout when Christian is back after Sept 12.

Thanks for the review!

**Pull request merged**
