### PR TITLE
ENH: Volume names in viewer

### PR DESCRIPTION
**Pull request by rweiss42**
self.viewNames was actually already being computed in onRefrenceChanged, you just weren't doing anything with it.  The slice viewer widget reserves a good amount of space for the slider and you'll see that the name of the series does get truncated if it's too long.

### CODE REVIEW

**Comment by fedorov** [comment]
Ok, so here's where some headaches are coming your way ...

You tried to commit a change to a checkout that conflicted with the current master, and you resolved the conflict by undoing my commits... How about you either checkout the current master and do your modification, or try to resolve the conflict more gracefully? ;)

**Comment by rweiss42** [comment]
hmmm... clearly i misunderstood the meaning of "their's"  interesting...

**Comment by rweiss42** [comment]
correct me if i'm wrong, but ultimately the result is what we want: one change in one file, no?

**Comment by fedorov** [comment]
There can be multiple changed files in one pull request, and multiple commits. What is important is that they are all related to one issue.

The problem with this pull request is that an earlier commit is reverted, if you see the list of commits (commit 1 in the list):    Revert "ENH: acknowledge Robin". Do you see what I mean?

**Comment by rweiss42** [comment]
yeah, i'm with you.  kill this pull request and I'll give it another go?

**Pull request closed without merging**
