### PR TITLE
BUG: Enable/disable the Segmentation tab when "Select All Series"/"De…

### PR DESCRIPTION
**Pull request by brikeats**
…select All Series" buttons are clicked. Fixes issue #111.

### CODE REVIEW

**Comment by fedorov** [comment]
Did you mean fixes #110?

Also, it only partially fixes #110, since it is possible to get to the situation when you have no series selected without clicking "Unselect all", just by unselecting them one by one.

**Comment by che85** [comment]
That would only fix a part of #110

The user could still deselect all series manually and the segmentation tab would still be enabled.

**Comment by brikeats** [comment]
Whoops, yeah, you're right on both counts. I had (incorrectly) assumed that I introduced the bug. I'll submit a separate pull request when I actually get it fixed.

**Comment by che85** [comment]
@fedorov I didn't see your reply. Sorry for the spam

**Comment by fedorov** [comment]
:) no worries, thanks!

**Comment by fedorov** [comment]
@brikeats feel free to follow up with a revision if you want to implement the suggestion from @che85

**Comment by fedorov** [comment]
@brikeats another suggestion, it would be nice to use this kind of "select/deselect all" control:

image

instead of the buttons at the bottom of the list

image

**Comment by che85** [comment]
I agree. Usually that series selection widget should not become that large, but there are some issues regarding the QTabWidget which always resizes all tabs to the biggest width/height. I am going to find out how we can fix this issue.

**Pull request merged**
