### PR TITLE
BUG: failing dcm2xml execution on Mac

### PR DESCRIPTION
**Pull request by che85**
- fixed Issue #55
- instead of using manual string concatenation for paths, now using os.path.join()
- using DICOMLib for execution of dcm2xml
- tested successful on Windows, Linux and Mac

### CODE REVIEW

**Comment by che85** [comment]
Anyway execution under Windows works for the very first time. Starting PCampReviewProcessor again, an error occurs regarding the deletion of the temporary path:

self.dataDir = os.path.join(slicer.app.temporaryPath, "PCampReviewPreprocessor")
shutil.rmtree(dataDir)

Somehow even when I execute this code manually after starting Slicer but without calling PCampReviewProcessor, Windows replies:

WindowsError: [Error 32] The process cannot access the file because it is being used by another process: u'C:/Users/CHRIST~1/AppData/Local/Temp/Slicer\\PCampReviewPreprocessor\\CtkDicomDatabase\\ctkDICOM.sql'

**Comment by fedorov** [comment]
Why is the second commit here? It is not related.

**Comment by che85** [comment]
That is strange. It was not my purpose to commit it here....

I deleted this commit yesterday. Maybe I did it wrong.

**Comment by fedorov** [comment]
looks like you are committing on master, you should instead be creating new branch for each fiture/issue you are resolving. Maybe this is the source of confusion.

**Comment by che85** [comment]
Yes I created another branch previously but committed here and deleted the commit locally without pushing it to the master.

**Comment by che85** [comment]
Ok I hope it is correct now

**Pull request merged**
