### PR TITLE
Improvement of User Experience

### LINKED ISSUE #73: Add labels to the segmentation step to indicate what data you are working with
In the old UI layout, we could see the titles of the previous steps which would show the user what data directory they're in and what patient/study was selected.  I'd like to add some labels (or something else?  suggestions?) either globally or just in step 4 to show that data directory you are in and what study you're currently working with.  Similar to how we added a label in step 2 to show what data directory you are currently in.

### LINKED ISSUE #104: Module panel is too wide
Unfortunately, it appears that the width is set to the maximum width, which is the Structures widget in the Editor module. On 15-inch mac retina screen, module panel steals over 50% of the screen width! 

The layout used there is QHBoxLayout, and it keeps getting wider with the recent modifications of the functinality. I guess it would be great not to use QHBoxLayout in this part of Editor, or use combination of icons and tooltips instead of long button labels. @pieper any other suggestions?

Sceenshot below is full width of 15-inch mac screen.

image

### LINKED ISSUE #106: Improve User Experience
I think we should talk about usability aspects.

Some proposed improvements:
1. Having only one tab for "data selection". The current approach is a waste of space and the user needs to interact more than needed. I would leave the first tab like it is and add another splitview below the study selection list view.
2. Simplifying the segmentation tab. I got the feeling that the segmentation tab is far too full. The fiducials table somehow is lost in that layout when you don't know about that (unexperienced users)

@fedorov @rweiss42 What do you think?

### PR DESCRIPTION
**Pull request by che85**
fixes #73 
fixes #104 
fixes #106

### CODE REVIEW

**Comment by fedorov** [comment]
@che85 :+1: I tested, and it looks great to me, thanks!

@brikeats let us know if you have any concerns. If I don't hear back from you, I plan to merge this pm.

**Comment by che85** [comment]
Added another commit which displays further information for selected study

**Comment by brikeats** [comment]
It looks good, but the latest commit (bb76e) doesn't work for me. It correctly highlights the study and collapses the study box, but no series are displayed. Here is the log:
[commit-bb76e-log.txt](https://github.com/SlicerProstate/mpReview/files/155666/commit-bb76e-log.txt)

The previous commit (b96ed1) looks good and functions correctly as far as I can tell.

**Comment by che85** [comment]
@brikeats Can you provide this dataset to me?

**Comment by che85** [comment]
@brikeats Can you try it with the most recent commit? A few minutes ago, I committed something.

**Comment by brikeats** [comment]
@che85 Yes, commit 8a6cb5 works fine. Do you still need the dataset?

**Comment by che85** [comment]
@brikeats No, I already found the reason for that. Thanks :)

**Comment by fedorov** [comment]
@brikeats thank you for testing!

@che85 are you done, is this ready for merging?

**Comment by che85** [comment]
@fedorov Yes I would say so. I am currently working on other issues. So I will be creating a new PR then.

**Pull request merged**
