### PR TITLE
ENH: More robust approach to setting label outline/filled

### PR DESCRIPTION
**Pull request by rweiss42**
I have noticed that sometimes this button simply stops working.  Not entirely sure why.  Also, in the current approach we are simply toggling the label outline button, not setting them uniformly across all slice viewers so i've seen situations where some get set to outline and some set to filled.  In theory linking the viewers should have taken care of this but it doesn't seem to...

### CODE REVIEW

**Comment by fedorov** [comment]
@pieper can you take a quick look? I am not sure the proposed change is better or more correct.

Also, I have not experienced the label outline to fail to toggle while using the module. Robin, is that reproducible?

**Comment by rweiss42** [comment]
Trying to re-produce but having a hard time.  Will see if I can figure out what I was doing when this behavior popped up.  It may have been caused by reloading our module (which as we've talked about, isn't exactly implemented correctly) so it may have left the editor in a weird state.

Maybe there's a different method in the editor I should be calling, but say you go into step4 with 2 sequences selected.  The default for the new slice widgets is to make labels filled.  You click the outline/fill button and each of the slice viewers toggles so now both are outlined.  Go back to step3 and select two additional sequences.  Go to step4 and the two old viewers will still be outlined but the two new ones will be filled.

**Comment by rweiss42** [comment]
Also having a hard time re-producing the lack of linking between viewers.  Again, might be due to a wonky state I managed to put slicer in.  

I think toggleLabelOutline() is probably fine, but I'm also proposing here that the button for filled/outline actually keep track of state, not just toggle from one to the next.  This way on entrance to step4 you know if the user had previously selected outline/filled and you can explicitly set outline or filled depending.  Assuming viewers are linked and that all works properly (which I have to assume it does since I can't seem to reproduce), then I admit that I don't need to iterate over all of the slice widgets, just need to set it on one and it should get picked up on the rest.

**Comment by fedorov** [comment]
I agree keeping track of the state is a good idea. Your scenario makes sense, it should indeed cause the problem, since the outline state is toggled for individual slices

So how about you change the code in setLabelOutline to grab all slice nodes, as done in editUtil, and toggle the state to be the same for all slice nodes? Basically, doing this https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/EditorLib/EditUtil.py#L209 instead of grabbing sliceWidgets. I think it is better than relying on slice views as linked, since it is changing the underlying data, not relying on UI state.

**Comment by rweiss42** [comment]
Good idea!  Much more direct.

**Comment by pieper** [comment]
Yes, sounds good to track state.

As a general note it would be good to add the method to EditUtil rather
than manipulating the slice nodes directly in the PCamp code.

https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/EditorLib/EditUtil.py#L207-L210

**Comment by rweiss42** [comment]
Sounds fine to me.  So the idea would be to add a method to EditUtil, setLabelOutline(self, bool), that would take a bool parameter which gets passed on to sliceNode.SetUseLabelOutline(bool) in a similar loop, correct?  Shall I put in a PR for this?

**Comment by pieper** [comment]
Yes, that would be awesome!

**Comment by fedorov** [comment]
Robin, I tried to make a change to your pull request to add import math, but failed miserably ... can't merge it now. Can you add that import and submit a new PR?

**Comment by rweiss42** [comment]
ok, this can be closed via pull request 37 which i branched off of the current master.  says can be auto merged

**Pull request closed without merging**
